import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "./hero";
import Logistics from "./logistics";
import Banks from "./banks"; 
import Medicals from "./medicals";
import Cafe from "./cafe";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero / >
      <Logistics/>
      <Banks/>
      <Medicals/>
      <Cafe/>
      
    </div>
  );
}
